services:
  db:
    image: postgres:14
    container_name: myapp_db
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: myapp_backend
    restart: always
    ports:
      - "${BACKEND_PORT}:4000"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - db

  frontend:
    build: ./frontend-next
    container_name: myapp_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - ./frontend-next/.env.local
    depends_on:
      - backend

volumes:
  postgres_data:
